In [1]:
import warnings
warnings.simplefilter(action='ignore')

In [2]:
import tensorflow as tf

### 1. 创建计算图

#### 1.1 创建常数

In [3]:
c = tf.constant(2, name='c')

In [4]:
c

<tf.Tensor 'c:0' shape=() dtype=int32>

#### 1.2 创建变量

In [5]:
var = tf.Variable(c + 5, name='var')

In [6]:
var

<tf.Variable 'var:0' shape=() dtype=int32_ref>

### 2. 执行计算图

In [7]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [8]:
print('c:', sess.run(c))
print('var:', sess.run(var))

c: 2
var: 7


In [9]:
print('c:', c.eval(session=sess))
print('var:', var.eval(session=sess))

c: 2
var: 7


In [10]:
sess.close()

### 3. 使用 with 语句打开 Session

In [11]:
c = tf.constant(2, name='c')
var = tf.Variable(c + 5, name='var')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('c:', sess.run(c))
    print('var:', sess.run(var))

c: 2
var: 7


### 4. placeholder

In [12]:
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height)

In [13]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area:', sess.run(area, feed_dict={width: 6, height: 8}))

area: 48


### 5. 创建多维 tensor

#### 5.1 创建一维 tensor

In [14]:
var = tf.Variable([0.4, 0.2, 0.4])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(var)
    print(result)

[0.4 0.2 0.4]


In [15]:
print(result.shape)

(3,)


#### 5.2 创建二维 tensor

In [16]:
var = tf.Variable([[0.4, 0.2, 0.4]])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(var)
    print(result)

[[0.4 0.2 0.4]]


In [17]:
print(result.shape)

(1, 3)


In [18]:
W = tf.Variable([
    [-0.5, -0.2],
    [-0.3, 0.4],
    [-0.5, 0.2]
])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(W)
    print(result)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [19]:
print(result.shape)

(3, 2)


### 6. 矩阵基本运算

#### 6.1 矩阵乘法

In [20]:
X = tf.Variable([[1.0, 1.0, 1.0]])
W = tf.Variable([
    [-0.5, -0.2],
    [-0.3, 0.4],
    [-0.5, 0.2]
])
product = tf.matmul(X, W)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("product:", sess.run(product))

product: [[-1.3  0.4]]


#### 6.2 矩阵加法

In [21]:
b = tf.Variable([[0.1, 0.2]])
product = tf.Variable([[-1.3, 0.4]])
result = product + b

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('result:', sess.run(result))

result: [[-1.1999999  0.6      ]]


#### 6.3 矩阵乘法与加法

In [22]:
X = tf.Variable([[1.0, 1.0, 1.0]])
W = tf.Variable([
    [-0.5, -0.2],
    [-0.3, 0.4],
    [-0.5, 0.2]
])
b = tf.Variable([[0.1, 0.2]])
result = tf.matmul(X, W) + b

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('result:', sess.run(result))

result: [[-1.1999999  0.6      ]]
